Issue/add notification UUID header to outgoing requests
open-zaak/open-notificaties pull request #101
Opened 2023-06-30 14:33 UTC by Nath82

#99 Add Notificatie.UUID, forward to subs with serializers and test it via test_notificatie and test_notifications.
We're adding a UUID to make it easier to find the notification across different platforms.

2023-07-03 21:46 UTC, alextreme requested changes
I'd prefer to avoid changing the OAS spec (even if the change makes sense). 

So fine that you added the uuid to the Notificatie and IMHO this is as intended, but the field can't be exposed via the API

2023-07-07 12:39 UTC, annashamray reviewed
This PR duplicates changes from https://github.com/open-zaak/open-notificaties/pull/71
What is the plan for https://github.com/open-zaak/open-notificaties/pull/71 now?

2023-07-24 14:16 UTC, alextreme approved these changes

2023-07-24 14:17 UTC, alextreme commented
The plan is to merge this PR and close PR #71 as mentioned in issue #99

2023-07-25 08:13 UTC, merged