Feature/flower
open-zaak/open-notificaties pull request #44
Opened 2021-09-10 09:34 UTC by annashamray

2021-09-10 10:25 UTC, sergei-maertens requested changes

2021-09-10 10:25 UTC, sergei-maertens commented on bin/celery_flower.sh
> +celery --app nrc --workdir src flower
```suggestion
exec celery --app nrc --workdir src flower
```

2021-09-10 10:25 UTC, sergei-maertens commented on bin/celery_flower.sh
> +#!/bin/sh
```suggestion
#!/bin/bash
```

2021-09-10 10:25 UTC, sergei-maertens commented on docker-compose.yml
> +      - celery
```suggestion
    depends_on:
      - rabbitmq
```

Flower connects to the broker

2021-09-10 19:28 UTC, joeribekker approved these changes

2021-09-14 09:38 UTC, sergei-maertens approved these changes

2021-09-14 10:59 UTC, merged